language: python

arch:
  - arm32

python:
  - "3.7"

services:
  - docker

install:
  - pip install pipenv
  - pipenv install

jobs:
  include:
    - stage: test
      skip_cleanup: true
      script: pipenv run; pytest
    - stage: deploy
      script: docker build -t xdronedsl/backend:latest .
      deploy:
        provider: script
        skip_cleanup: true
        script: bash docker_push.sh
        on:
          branch: master

notifications:
  email: false
